[package]
name = "freude_derive"
version = "0.1.0"
authors = ["Richard Janis Goldschmidt <janis.beckert@gmail.com>"]

[lib]
name = "freude_derive"
proc-macro = true

[dependencies]
syn = "0.11"
quote = "0.3"

[dev-dependencies]
freude = { path = ".." }
