[package]
name = "freude"
version = "0.2.1"
authors = ["Superfluffy"]
license = "MIT/Apache-2.0"

repository = "https://github.com/SuperFluffy/rust-freude"

description = "Something that is supposed to develop into a fully fledged ODE library."

keywords = ["ODE", "numerics", "ndarray", "rungekutta", "euler"]
categories = ["science"]

[lib]
name = "freude"

[dependencies]
itertools = "0.4"
ndarray = "0.8"

[dev-dependencies]
approx = "0.1"
