[package]
name = "freude"
version = "0.1.1"
authors = ["Superfluffy"]
license = "MIT/Apache-2.0"

repository = "https://github.com/SuperFluffy/rust-freude"

description = "Something that is supposed to develop into a full fledges ODE library."

keywords = ["ODE", "integrator", "numerics", "ndarray", "rungekutta", "rk4", "euler", "heun"]
categories = ["science"]

[lib]
name = "freude"

[dependencies]
itertools = "0.4"
ndarray = "0.7"

[dev-dependencies]
approx = "0.1"
