[package]
name = "freude"
version = "0.2.1"
authors = ["Superfluffy"]
license = "MIT/Apache-2.0"

repository = "https://github.com/SuperFluffy/rust-freude"

description = "Something that is supposed to develop into a fully fledged ODE library."

keywords = ["ODE", "numerics", "ndarray", "rungekutta", "euler"]
categories = ["science"]

[lib]
name = "freude"

[dependencies]

[dependencies.ndarray]
version = "0.9"

[dev-dependencies]
approx = "0.1"
blas = "0.15"
ndarray-rand = "0.5"
rand = "0.3"
